#!/bin/bash

FILE=antlr-4.7.1-complete.jar
if [[ ! -f ${FILE} ]]; then
    curl -O https://www.antlr.org/download/${FILE}
fi
java -cp antlr-4.7.1-complete.jar org.antlr.v4.Tool -package com.oracle.truffle.sl.parser -no-listener language/src/main/java/com/oracle/truffle/sl/parser/SavoLanguage.g4